import type { PrivacyPolicy } from './types';

export const privacyEn: PrivacyPolicy = {
  title: 'Privacy Policy — Damas Evolution',
  updatedLabel: 'Last updated:',
  updatedDate: 'September 23, 2026',
  intro: [
    'This Privacy Policy describes how the **Damas Evolution** app ("app", "we"), developed by **Leankar.dev** ("Developer"), handles user information. It applies to the app on Android and Windows and to the Damas Evolution website. By using the app or the website, you agree to this policy.',
  ],
  sections: [
    {
      title: '1. Summary',
      blocks: [
        {
          type: 'paragraph',
          text: 'Damas Evolution **does not collect, transmit or share personal data**. The app works entirely offline and all information generated by you stays exclusively on your device. The website does not collect personal data either (see section 5).',
        },
      ],
    },
    {
      title: '2. Data we do NOT collect',
      blocks: [
        {
          type: 'list',
          items: [
            'We do not require registration, login or a user account.',
            'We do not collect name, email, phone number, location, contacts, photos, files or any other personal data.',
            'We do not collect advertising identifiers or device identifiers.',
            'We do not use third-party analytics, crash reporting, advertising or tracking services.',
            'We do not sell, rent or share information with third parties.',
          ],
        },
      ],
    },
    {
      title: '3. Data stored locally on the device',
      blocks: [
        {
          type: 'paragraph',
          text: "To make the game work, the app stores only the following in your device's local storage:",
        },
        {
          type: 'list',
          items: [
            '**Match history:** game mode (against the AI or local multiplayer), winner, total number of moves, AI difficulty level and match date/time. This data powers the statistics screen.',
            '**Preferences:** AI difficulty level, sound on/off, 3D board usage and language.',
          ],
        },
        {
          type: 'paragraph',
          text: 'This data **never leaves your device** and is not accessible to the Developer.',
        },
      ],
    },
    {
      title: '4. Permissions',
      blocks: [
        {
          type: 'paragraph',
          text: 'The app does not request any sensitive Android or Windows permission (such as camera, microphone, location, contacts or external storage). The app does not require internet access to be played.',
        },
      ],
    },
    {
      title: '5. Website',
      blocks: [
        {
          type: 'paragraph',
          text: "The Damas Evolution website is static. It does not use cookies, analytics, advertising or third-party scripts, has no forms or accounts, and does not ask for your data. If you choose a light or dark theme, that preference is saved only in your browser's local storage and is never sent to us. If you email us, we use your address only to reply.",
        },
        {
          type: 'paragraph',
          text: "The website is served by a third-party hosting provider, which may record technical access data (such as IP address, date and time, and requested page) in its server logs for security and operation. We do not use those records to identify visitors; see the provider's own policy for details.",
        },
      ],
    },
    {
      title: '6. External links',
      blocks: [
        {
          type: 'paragraph',
          text: "The app and the website may offer links to third-party sites, such as the Developer's website ({developerUrl}) and the app's pages in app stores, opened in your device's browser. By accessing them, you become subject to those sites' privacy policies, over which we have no control.",
        },
      ],
    },
    {
      title: '7. Children',
      blocks: [
        {
          type: 'paragraph',
          text: "The app does not collect personal data from any user, including children and teenagers. Since nothing is collected, no minors' data is stored or processed by us.",
        },
      ],
    },
    {
      title: '8. Security',
      blocks: [
        {
          type: 'paragraph',
          text: "Because data remains on the device, its security depends on the device's own protections (screen lock, system encryption, etc.). The app does not write passwords, tokens or sensitive information to logs.",
        },
      ],
    },
    {
      title: '9. Your rights and data deletion',
      blocks: [
        {
          type: 'paragraph',
          text: "You can delete all app data at any time by clearing the app's storage in Android settings (Settings > Apps > Damas Evolution > Storage > Clear data) or by uninstalling the app. On Windows, uninstall the app in Settings > Apps; if any app data remains in your user account, you can delete it manually. Since we keep no data on servers, there is nothing to delete on our side.",
        },
      ],
    },
    {
      title: '10. Changes to this policy',
      blocks: [
        {
          type: 'paragraph',
          text: 'We may update this policy from time to time. The date of the last update will always appear at the top of this document. Relevant changes will be published on this same page.',
        },
      ],
    },
    {
      title: '11. Contact',
      blocks: [
        {
          type: 'paragraph',
          text: 'Questions about this policy: **{email}** · {developerUrl}',
        },
      ],
    },
  ],
};
